# Generated by Django 5.2.8 on 2026-03-10 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Procent de reducere oferit de acest achievement (ex: 10 pentru 10%)')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='brands/heroes/')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('categories', models.ManyToManyField(blank=True, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('role', models.CharField(blank=True, help_text="Trupa și rolul, ex: 'Guns N Roses – Lead Guitar'", max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, help_text='Citat celebru pentru design high-end', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='artists/heroes/')),
                ('brands', models.ManyToManyField(blank=True, related_name='artists', to='catalog.brand')),
                ('products', models.ManyToManyField(blank=True, related_name='artists', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('title', models.CharField(default='Novice', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_unlocked', models.DateTimeField(auto_now_add=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.achievement')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='users_unlocked',
            field=models.ManyToManyField(blank=True, related_name='achievements', through='catalog.UserAchievement', to='catalog.userprofile'),
        ),
    ]
