# Generated by Django 5.2.8 on 2026-04-15 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('page_view', 'Vizualizare Pagină'), ('product_view', 'Vizualizare Produs'), ('search', 'Căutare'), ('add_to_cart', 'Adăugare în Coș'), ('purchase', 'Achiziție'), ('register', 'Înregistrare'), ('login', 'Autentificare')], db_index=True, max_length=50)),
                ('session', models.CharField(blank=True, max_length=120, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('page', models.CharField(blank=True, max_length=500, null=True)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activitate',
                'verbose_name_plural': 'Activitate Site',
                'ordering': ['-created_at'],
            },
        ),
    ]
