# Generated by Django 5.2.8 on 2026-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_site_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteActivityProxy',
            fields=[
            ],
            options={
                'verbose_name': '📊 Dashboard Statistici',
                'verbose_name_plural': '📊 Dashboard Statistici',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.siteactivity',),
        ),
        migrations.AddField(
            model_name='order',
            name='awb_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, default='FBG Express', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('confirmed', 'Confirmat'), ('shipped', 'Expediat'), ('delivered', 'Livrat'), ('cancelled', 'Anulat')], default='confirmed', max_length=20),
        ),
    ]
